FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

WORKDIR /go/src/practice-3
COPY . .

# TODO: Змініть на власну реалізацію системи збірки
RUN go get -u github.com/Vlad1slavIP74/2lab/build/cmd/bood

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
ENTRYPOINT ["bood", "integration-tests"]
ENTRYPOINT ["echo", "ok"]
