FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/Vlad1slavIP74/2lab/build/cmd/newbood

WORKDIR /go/src/practice-3
COPY . .

RUN ["chmod", "+x", "./integration-test.sh"]
RUN ["chmod", "+x", "./usr/bin/foxx"]
ENTRYPOINT ["./integration-test.sh"]
